apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-claim
  namespace: wordpress
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-claim
  namespace: wordpress
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
